### PR TITLE
Create MANIFEST.in

### LINKED ISSUE #4: requirements.txt is not included in the tarball on PyPI
And `setup.py` fails.

### PR DESCRIPTION
**Pull request by robertodr**
Fix #4

### CODE REVIEW

**Comment by rkdarst** [comment]
Thanks!  I guess this is another reason for including it directly in requirements.txt...

**Comment by robertodr** [comment]
Will you make a new minor release with this change?

**Comment by robertodr** [comment]
:sweat_smile: I see the new tag, but I think the release action failed :(

**Comment by rkdarst** [comment]
Arg, I bumped the version, but when resolving the rebase I forgot to
commit it (... I was also adding the manifest at the same time).

Anyway, it is released now.  Thank you for your help and noticing
this!

**Comment by robertodr** [comment]
Thanks! The Sphinx lesson has the same problem: https://github.com/coderefinery/sphinx-lesson/pull/46

**Comment by rkdarst** [comment]
sphinx-lesson now also updated

**Pull request merged**
